with exceptions.NullAccess
with tyr.io.System.out

/**
 * @note tests correctness of try catch
 */
class T <: Exception {
  // note: implicit throw has been removed since the straight-forward use case
  // does not work atm. (see implicitExceptions tests)

  test "explicit throw no handler" {
    try {
      throw new T
    } catch e {
      if NullAccess {
        delete e
        false
      }
      else {
        delete e
        true
      }
    }
  }

  test "explicit throw" {
    try {
      throw new T
    } catch e {
      if NullAccess {
        delete e
        false
      }
      if T {
        delete e
        true
      }
      else {
        delete e
        false
      }
    }
  }

  test "no throw" {
    try {
      new T
      true
    } catch e {
      if NullAccess {
        delete e
        false
      }
      if T {
        delete e
        false
      }
      else {
        delete e
        false
      }
    }
  }
}
